#!/bin/bash

echo "`date` INFO: kvmd-first starting"

# Fix permissions
chmod a+rw /dev/gpio*
chmod a+rw /dev/spi*
#chown kvmd-webterm /home/kvmd-webterm
#chown kvmd:kvmd /etc/kvmd/htpasswd
#chown kvmd-ipmi:kvmd-ipmi /etc/kvmd/ipmipasswd
#chown kvmd-vnc:kvmd-vnc /etc/kvmd/vncpasswd
#chown kvmd:kvmd /etc/kvmd/totp.secret

# Change hostname for kvmd GUI
sed -i -e "s/    host: .*/    host: $HOSTNAME/g" /etc/kvmd/meta.yaml

# Delete temporary extras file, need to be deleted at each start
rm -f /tmp/systemctl-kvmd.txt

# Check kvmd-otg, otherwise it can give an error
# if /sys/kernel/config/usb_gadget/kvmd then skip
# if ! /sys/kernel/config/usb_gadget/kvmd then rm /run/kvmd/otg

if [ ! -d "/sys/kernel/config/usb_gadget/kvmd" ]; then
  if [ -d "/run/kvmd/otg" ]; then
    echo "`date` WARN: USB gadget is NOT enabled, but /run/kvmd/otg exist ... Deleting it"
    rm -rf /run/kvmd/otg
  fi
else
  # We should stop kvmd-otg.service, should prevent issues?
  systemctl stop kvmd-otg.service
fi

# Check if /storage.img exist, then run a mount. Otherwise the kvmd will fail
if [ -f "/storage.img" ]; then
  mount -a
fi

exit 0
