#!/usr/bin/python
# -*- coding: utf-8 -*-
import re
import sys
import os
from kvmd.apps.janus import main
if __name__ == '__main__':
    os.umask(0o002)
    sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])
    sys.exit(main())
